/**
 * @file tuya_config_example.h
 * @brief IoT specific configuration file - EXAMPLE TEMPLATE
 *
 * @attention This is a template file!
 * @attention Copy this file to tuya_config.h and fill in your actual credentials
 *
 * HOW TO USE:
 * 1. Copy this file: cp tuya_config_example.h tuya_config.h
 * 2. Edit tuya_config.h with your real credentials from Tuya IoT platform
 * 3. Do NOT commit your actual tuya_config.h file!
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

#include "tuya_cloud_types.h"

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, create on the Tuya IoT platform
 * TUYA_OPENSDK_UUID: UUID, the unique ID of the device, you can get 2 free from Tuya IoT platform
 * TUYA_OPENSDK_AUTHKEY: AUTHKEY, the private key of the device, you can get 2 free from Tuya IoT platform
 *
 * detail please refer to: https://developer.tuya.com/cn/docs/iot-device-dev/application-creation?id=Kbxw7ket3aujc
 *
 * warning: please replace these production information with your product id and license, otherwise the demo cannot
 * work.
 *
 */

#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID "your_product_id_here"
#endif

#define TUYA_OPENSDK_UUID    "your_uuid_here"    // Replace with your UUID from Tuya IoT platform
#define TUYA_OPENSDK_AUTHKEY "your_authkey_here" // Replace with your AUTHKEY from Tuya IoT platform

/**
 * @brief PINCODE for AP provisioning
 *
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 *
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "12345678"

#endif
